### ISSUE TITLE
Ocra built executables take a minute to launch on Win8 / Win10

### ISSUE THREAD

**Issue by shawn42** [larsch/ocra#105]
When launching my Gosu game executable on Windows 8 or Windows 10 the game takes about a minute to launch but launches in a few seconds on Windows 7.

Links to the windows build and the source can be found here:
http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=571

Any ideas on what could be causing this? and / or any work arounds?

**Comment by shawn42** [comment]
@larsch My testing on Win8 shows that the first run in about 60s (in a VM). Subsequent runs are about 5s. Possibly a delay while windows loads legacy libraries? Maybe we need a pre-win8 build and a post-win8 build of ocra?

**Comment by larsch** [comment]
I'm not seeing this on Windows 10. In my experience, Windows Defender and other virus scanners are quite aggressive with "Unknown" executables - perhaps this is causing the slow down. You could try and monitor the executable with procmon from sysinternals, so we can see what's going on.

**Comment by shawn42** [comment]
@larsch Can you try the Windows link from my Gosu game packaged up with ocra: http://ludumdare.com/compo/ludum-dare-33/?action=preview&uid=571  Also, can you post the exe you are using for testing and I can test it on my setup. Thanks again!

**Comment by jlnr** [comment]
13 seconds in my Windows 10 VM, running off an external HD via VirtualBox (which tends to be slow). So definitely faster than for you @shawn42, but still not as snappy as it should be.

**Comment by shawn42** [comment]
@jlnr thanks for the data point, do you have a copy of win8 to test on?

**Comment by jlnr** [comment]
Nope, I think what matters more is whether I have Windows Defender running or not. I honestly don't know :) I'll verify that first.

**Comment by shawn42** [comment]
I was able to test this on my new Win10 machine (with defender on) and the game starts in a few seconds. I will retest on Win8 and post my findings.

**Comment by larsch** [comment]
Assuming no longer pertinent, closing.
