### ISSUE TITLE
Windows PE Header

### ISSUE THREAD

**Issue by rsecka** [larsch/ocra#112]
Hallo,
i want to my EXE File created by OCRA will have Windows PE header (File Version, Product Version, Comments, Copyright .. )

Is there any way I can add this information?

When I for example try to add this iformations with verpatch (verpatch.exe path_to_exe /va ve.rs.io.n)
than application come with Fatal Error: invalid opcode.

**Comment by rsecka** [comment]
Duplicate to: https://github.com/larsch/ocra/issues/63

**Comment by ismendoza** [comment]
I want to to the same (File Version, Product Version, Comments, Copyright .. ) but #63 doesn't resolve
