### ISSUE TITLE
Unable to Use Ocra With watir-webdriver 

### ISSUE THREAD

**Issue by pfw3001** [larsch/ocra#116]
Hi all

when I use Ocra with watir-webdriver, I meet this issue:

my codes : (test.rb)

```
require 'watir-webdriver'

browser = Watir::Browser.new :chrome
browser.goto "http://www.baidu.com"
```

my compile command : 
`ocra test.rb`

generate : test.exe

click the test.exe, then : 

```
.....
from C:/users/wpan/AppData/Local/Temp/ocrE14F.tmp/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
from C:/users/wpan/AppData/Local/Temp/ocrE14F.tmp/src/test.rb:1in `<main>
......
```

it's very confuse me, watir-webdriver could be use ?

**Comment by larsch** [comment]
Unable to reproduce with Ocra 1.3.7, ruby 2.2.6p396, watir 6.2.0. watir-webdriver is deprecated, so I didn't try it.
