### ISSUE TITLE
'gem install ocra' gets older version without Inno Setup fix

### ISSUE THREAD

**Issue by skwilson** [larsch/ocra#117]
I am trying to setup a simple procedure for the Windows folks at work to build releases. If I do 'gem install ocra' in a Windows command window it gets a version without the fix for IGNORED_MODULES for Inno Setup. This means, of course, that it fails.

What needs to be done to get the latest version on rubygems?

**Comment by larsch** [comment]
Lots of releases since this. Please help with additional info if this is still an issue.
