### ISSUE TITLE
Error on executing exe "not compatible with the version of windows your're running"

### ISSUE THREAD

**Issue by EmiliocGarcia** [larsch/ocra#124]
After using ocra to create exe file I get the following errors during the process.

1. shows an "io-console" error

2. shows what happens when I attempt to run the exe file.
![capture2](https://user-images.githubusercontent.com/28538533/28532751-51f0c1c4-7060-11e7-9b7f-4f90a6967bdb.PNG)
![capture](https://user-images.githubusercontent.com/28538533/28532756-560dbfb4-7060-11e7-8d6c-742f997ea641.PNG)

**Comment by mshem** [comment]
I am getting this same error, on Windows 10. 'The specified executable is not a valid application for this OS platform.'

**Comment by endymion** [comment]
Same problem.  Ruby 2.0.0 and 32-bit Windows 10.

**Comment by grizzer** [comment]
Same. Ruby 2.4.1p111 on 32-bit Win7.

**Comment by phlundblom** [comment]
This broke in latest Ocra release (1.3.9). Seems like all previous versions had the Windoze stub binaries (stub.exe, stubw.32 and edicon.exe) built as 32-bit binaries while the latest release is built for x86-64.

**Comment by jjgh** [comment]
Having the same issue. This is critical! Does anyone have a quick patch?

I am on a Windows 7 32 bit where I installed Ruby and the ocra gem to produce a 32 bit exe, but I'm getting the error mentioned above.

**Comment by jjgh** [comment]
Ok as a workaround I took the files mentioned by @phlundblom from ocra 1.3.8, then reinstalled ocra 1.3.9 and copied them in C:\Ruby24\lib\ruby\gems\2.4.0\gems\ocra-1.3.9\share\ocra and it worked.
Going back to the 1.3.8 gem is a no go because of the "failed to create process" problem.

**Comment by larsch** [comment]
Fixed in 1.3.10.
