### ISSUE TITLE
Use Github Actions

### ISSUE THREAD

**Issue by circutrider21** [larsch/ocra#153]
I have looked at this repository, and one recommendation i have is to use GitHub Actions, which would improve your workflow.

**Comment by larsch** [comment]
Thanks for the recommendation!

**Comment by larsch** [comment]
Is running the OCRA unittest on a CI practical? I needs MinGW and ideally multiple versions of RubyInstaller available. Also, needs the ability to build and run Windows executables.

**Comment by circutrider21** [comment]
You can do all that you have mentioned above by specifying what you need to do your test on a CI.
Finally, you can use GitHub artifacts to upload the files generated by the CI to GitHub releases
