### ISSUE TITLE
cannot load such file -- rubygems.rb

### ISSUE THREAD

**Issue by sevenc-nanashi** [larsch/ocra#155]
I made executable app with this.
But, it returned error.
This is an error code:
> <internal:gem_prelude>:4:in `require': cannot load such file -- rubygems.rb (LoadError)
>         from <internal:gem_prelude>:4:in `<internal:gem_prelude>'

I tried to add source "require "rubygems"".

I want to use gems.
So, I don't want to use "--disable-gems".

Please help me!
(I'm Japanese, so maybe this text isn't good.I'm sorry.)

**Comment by larsch** [comment]
Need more details in order to be able to reproduce. Run ocra with `--verbose` and provide logs. Please also provide any environment variables (output of `set` command). It could be another localization issue.

**Comment by sevenc-nanashi** [comment]
https://pastebin.com/0m7NKa2K
I used `--verbose` command, and copied log.

**Comment by sevenc-nanashi** [comment]
**Set command**
I won't all of `set`'s result.
So I want what you need.

**Comment by sevenc-nanashi** [comment]
I ran the program at Japanese username PC.
So Maybe this is reason of this program.
I will try at English username PC!
Thank you!
