### ISSUE TITLE
YAML files not included

### ISSUE THREAD

**Issue by fabiopavan** [larsch/ocra#158]
Hi, larsh. I'm trying to compile a program, but YAML files are not included. They reside in *setup* folder. I wrote this command:

`ocra kernel.rb lib/* setup/*  --add-all-core --gem-full`

The executable cannot find the YAML files, showing that they weren't included.

**Comment by larsch** [comment]
Unable to reproduce. 

This works fine:

```ruby
require "yaml"
p YAML.load_file(File.dirname($0) + "/setup/test.yaml")
```

```
C:\Users\larsch> D:\src\ocra\samples\yaml_test.exe
{"a"=>"b", "c"=>"d"}
```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36108241/77269059-8fab3100-6c86-11ea-8afd-2d2b5b5c3860.png)

Doing what you did, it works. But doing it like my source code, no way. I tried to use the following command:

`ocra kernel.rb --add-all-core --gem-full`

Then this:

`ocra kernel.rb setup/* lib/* --add-all-core --gem-full`

No way.

**Comment by imbrish** [comment]
You're trying to read relative to called executable `$0` instead of relative to unpacked script `__FILE__`.

**Comment by ghost** [comment]
Oops, that's right, imbrish. I want to have the YAML files inside the executable.
