### ISSUE TITLE
Doesn't find all dlls loaded by Ray

### ISSUE THREAD

**Issue by Spooner** [larsch/ocra#34]
[Ray](https://github.com/Mon-Ouie/ray) is an opengl based game-development library. When running normally, it loads a number of dlls on Windows correctly, but when made into an exe, Ocra finds all but one of them (using Ruby 1.9.2, Ocra 1.3.0, Ray 0.2.0).

<pre>
=== Adding detected DLL C:/Ruby192/bin/libiconv2.dll
=== Adding detected DLL C:/Ruby192/lib/ruby/gems/1.9.1/gems/ray-0.2.0/ext/freetype6.dll
=== Adding detected DLL C:/Ruby192/bin/zlib1.dll
=== Adding detected DLL C:/Ruby192/lib/ruby/gems/1.9.1/gems/ray-0.2.0/ext/glew32.dll
=== Adding detected DLL C:/Ruby192/lib/ruby/gems/1.9.1/gems/ray-0.2.0/ext/libsndfile-1.dll
=== Adding detected DLL C:/Ruby192/bin/libeay32-1.0.0-msvcrt.dll
=== Adding detected DLL C:/Ruby192/bin/ssleay32-1.0.0-msvcrt.dll
</pre>

It does not find OpenAL32.dll however (though I can include it manually and add it to the path at run-time and that works OK, it would perhaps prevent other users from using the library).

Relevant file is probably https://github.com/Mon-Ouie/ray/blob/master/lib/ray/ray.rb (adds dll directory at the correct end of the path, so it should load its own dlls before the system ones).

The only oddity is that the OpenAL32.dll is originally named soft_oal.dll, but it is renamed when the gem is installed, unlike all the other dlls (https://github.com/Mon-Ouie/ray/blob/master/ext/extconf.rb)

Thanks for any thoughts on the matter!

**Comment by larsch** [comment]
Sorry for late response. Perhaps the DLL is loaded late, and not at all when running Ocra. You can supply the path to the dll when running Ocra and it should be included.
