### ISSUE TITLE
Rails 3.2rc1 - No such file to load `bundler/setup`

### ISSUE THREAD

**Issue by Philipp15b** [larsch/ocra#44]
After starting my packaged Rails 3.2rc1 application, I got an the error message: No such file to load `bundler/setup`. I've used the command from the README to package it.

**Comment by larsch** [comment]
Closing - assumed solved.

**Comment by damian-m-g** [comment]
This is happening in last Ocra version (in this moment it's 1.3.11), compiling with Ruby 3.1 x64 Windows build. The ocra executable was run from a machine that doesn't have Ruby installed and it seems to look for _bundler/setup_ in the usual Ruby's install directory, which of course, doesn't exist in this machine.

![image](https://user-images.githubusercontent.com/1852056/150839204-b214d15e-fe24-4700-815f-99fbcb1d8a0f.png)

If I make the user install Ruby 3.1 x64 Windows build, it works. The script wasn't compiled with _--no-deep-run_, and it uses _--gem-full_. Full command minus scripts requirement:

`ocra --add-all-core --gem-full --dll ruby_builtin_dlls/zlib1.dll --dll ruby_builtin_dlls/libssp-0.dll --dll ruby_builtin_dlls/libgmp-10.dll  --chdir-first`
