### ISSUE TITLE
jRuby is a beach.

### ISSUE THREAD

**Issue by JellybeanDream** [larsch/ocra#49]
It appears as though jRuby is conflicting with ocra in some way, i was unable to compile anything until i completely uninstalled jruby.

Just a heads up if you're using both.

**Comment by jjgh** [comment]
Possibly related to this https://groups.google.com/d/msg/ruby-ocra/S_dFbT900CY/iMj1KskJlEIJ ?

**Comment by larsch** [comment]
Thanks for the heads up.
