### ISSUE TITLE
Facing Error while creating exe- Undefined method full_name

### ISSUE THREAD

**Issue by anbublacky** [larsch/ocra#50]
Command Used:
ocra projname\script\rails projname --output iscrm.exe --add-all-core --gemfile projname\Gemfile --no-dep-run --chdir-first --gem-all --windows --no-lzma --innosetup iscrm.iss -- server

This is the error i'm facing

C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin/ocra:623:in `block in find_gem_files': undefined method`full_name' for nil:NilClass (NoMethodError)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin
/ocra:581:in `each'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin
/ocra:581:in`find_gem_files'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin
/ocra:701:in `build_exe'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin
/ocra:1138:in`block in <top (required)>'

Full details can be found here:
http://paste.debian.net/175275/

Please someone help me to solve this issue.

**Comment by larsch** [comment]
Closing - assuming outdated.
