### ISSUE TITLE
Bad file descriptor

### ISSUE THREAD

**Issue by ghost** [larsch/ocra#52]
Whenever I try and compile anything with OCRA, I get this error:

=== Compressing 5914523 bytes
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ocra-1.3.0/bin/ocra:1005:in 'write': Bad file descriptor - RubyRPG1-6.exe (Errno::EBADF)
 from ocra:1005:in 'block in initialize'
 from ocra:983:in 'open'
 from ocra:983:in 'initialize'
 from ocra:822:in 'new'
 from ocra:822:in 'build_exe'
 from ocra:1138: in 'block in (top (required))'

Then it creates a 34KB .exe with a bad file signature. This is happening no matter where I try to compile, in Downloads or Desktop, even when I run it as administrator, even when I try and compile .rbs I have previously successfully compiled .exes of. Normally I recall this error message popping up if there was already a .exe with that file name in the directory, but I make sure to delete or rename any duplicate files before I run the compiler.

I am running Windows 7 Ultimate 64-bit with SP1.

**Comment by larsch** [comment]
Closing - lack of info, no way to reproduce.
