### ISSUE TITLE
TypeError: Unable to resolve type 'B'

### ISSUE THREAD

**Issue by pbharadiya** [larsch/ocra#67]
Hi, 
I am getting following error while running > ocra --no-autoload test1.rb

TypeError: Unable to resolve type 'B'

I am using Windows 8 and Ruby 2.0.0p353.

Can anyone help me?

Thanks.

**Comment by larsch** [comment]
Please reopen with more info if still an issue.

**Comment by DenisTukhvatshin** [comment]
I had a similar problem. I fixed it all by restarting the Visual Studio. Thanks
