### ISSUE TITLE
Ignoring <gem_name> because its extensions are not built.

### ISSUE THREAD

**Issue by wstaples** [larsch/ocra#74]
When attempting to run a script compiled with ocra I receive the following error:

`Ignoring ruby-odbc-0.99995 because its extensions are not built.  Try: gem pristine ruby-odbc-0.99995`

The script was built with `ocra --gem-full my_script.rb`
I have included 

``` ruby
require 'sequel'
require 'odbc'
```

This worked several months ago I'm not sure if something was changed in the script or new versions of gems. I did not have the require 'odbc' before I added it as a test. I have also tried uninstalling / reinstalling the odbc gem with no luck. any help would be appreciated.

This is also an issue for a different script that uses the mysql2 gem. I would suspect any gem that needs native extensions would be affected. 

I was however able to work around this issue by "downgrading" to ruby gems 2.1.0 on a hunch after reading this thread. 

https://github.com/rubygems/rubygems/issues/977

I am running Windows 7 64-bit with Ruby 1.9.3 (2013-06-27 patchlevel 448) [i386-mingw32]
I was running ruby gems 2.3.0 which did not work. I tried upgrading to 2.4.1 which also did not work.

**Comment by matthewcummings** [comment]
That worked for me as well, thank you!

**Comment by wstaples** [comment]
I'm still having this exact issue on Windows 7 64bit
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]
gem 2.5.1
ocra 1.3.6

I know its been a while but any help would be appreciated.

**Comment by bgura** [comment]
Having same issue. Windows 7 64bit
ruby 2.2.2p95 [x64-mingw32]
ocra 1.3.6

Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    confluence-client (0.0.8)
    i18n (0.7.0)
    jira-ruby (0.1.18)
      activesupport
      oauth (~> 0.4.7)
    json (1.8.3)
    minitest (5.9.0)
    oauth (0.4.7)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  x64-mingw32

DEPENDENCIES
  confluence-client
  jira-ruby
```

**Comment by HaleTom** [comment]
For the googlers out there:

`gem pristine --all` fixed analogous errors for me.

I was running on Linux, so needed to:
```
sudo bash # needed if getting permission errors and using chruby to load .bashrc 
gem pristine --all
