### ISSUE TITLE
Problem loading default gems

### ISSUE THREAD

**Issue by monkeysuffrage** [larsch/ocra#78]
When I try to load psych (a default gem in 2.1) I get:
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/ocra-1.3.2/bin/ocra:86:in `open': No such file or directory @ dir_initialize - C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/psych-2.0.5 (Errno::ENOENT)

**Comment by larsch** [comment]
I believe this to be fixed with the 2.1.5 workarounds. Else please reopen.

**Comment by danielhickman** [comment]
I'm still getting `Ignoring json-1.8.3 because its extensions are not built. Try gem pristine json --version 1.8.3` when double clicking the generated exe file.

Version: Ocra 1.3.6
Ruby Version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
