### ISSUE TITLE
.exe does not run when copied to a new location

### ISSUE THREAD

**Issue by nhaberly** [larsch/ocra#88]
An .exe file that ocra creates runs from the location where it was created but does not run if I move it to some other Windows folder, i.e. my windowed Ruby app is not displayed. It does not make a difference if I click on the .exe or type the .exe file name in a command window. In this instance, the main Ruby script is referencing several files. I was referencing the sub-folders on the ocra command with lib/* data/* icons/*. I tried moving every file into the same folder and re-building the .exe and that did not help. I tried --chdir-first and that did not help. Adding $LOAD_PATH.unshift File.dirname($0) did not help. --debug did not display any information. How can I troubleshoot this problem to see why the .exe does not run after it is moved? Thank  you.

**Comment by scriptwizard99** [comment]
There is a debug option you can pass to the ocra command that will cause it to leave the temporary extracted dir there after it is done. In my experience, it has always been a dir named ocraXXXX or some such in the current directory. I'll bet you can find that there are files missing from that dir which your application expects. 

I had to play with this quite a lot to get my Ruby/Tk application to run properly. It was a pain, but now it works and I couldn't be happier. I am soooo glad ocra exists.

**Comment by nhaberly** [comment]
Yes, --debug-extract! I'll try your suggestion. Good idea! Thanks!

Date: Sun, 1 Mar 2015 19:36:28 -0800

**Comment by scriptwizard99** [comment]
This is what I eventually wound up with. Seems overkill, but it worked.

https://github.com/scriptwizard99/AlamazeTurnParser/blob/master/dist.bat

**Comment by nhaberly** [comment]
Thank you again.
I'm glad to see that you could package files found multiple levels below your main program --- I'm doing the same thing and I thought that be a problem for ocra.
Thanks so much.

Date: Sun, 1 Mar 2015 19:45:25 -0800

**Comment by nhaberly** [comment]
This was NOT an ocra issue. This was an issue where my application was not finding a required file at start-up time.
