### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by ashes999** [larsch/ocra#98]
Hi,

I would really like Ocra to work on Linux, as it's the only viable packager I have for my app right now (which requires native-extension gems).

Is this possible?

This may be related to the [issue for OSX support](https://github.com/larsch/ocra/issues/5), which is quite dated but still open.

**Comment by larsch** [comment]
It's not impossible, but difficult to get right for a number of reasons. First of, you need the Ruby executables (which are not included with Ocra), and a way to reliably know which .so, .dlls etc are needed, which is done by actually running the script with Ruby on Windows and monitor what it loads. Perhaps it could be done with Wine.

**Comment by thisismydesign** [comment]
+1

**Comment by larsch** [comment]
Again, not a bad idea, but a portable Ocra would be something different from what it is now.
