### ISSUE TITLE
Failed to create process

### ISSUE THREAD

**Issue by scriptwizard99** [larsch/ocra#99]
Have you ever seen an error like this?

![failedtocreateprocess](https://cloud.githubusercontent.com/assets/10767082/8636192/fbe3ac14-2819-11e5-80e3-60550f80cfcc.png)

I hope the answer is _"yes, dummy, do XYZ and everything will be fine"_. Otherwise, I'll try to get you more information. I'm still trying to get the user to tell me what version of windows he's running. 

The binary he is running was created via this command on 32 bit Vista service pack 2:
`ocra --no-autoload --add-all-core amap.rbw *.rb lib\* data\* graphics\* c:\ruby193\lib\tcltk`

I'm running ruby 1.9.3p551 and ocra 1.3.5

**Comment by basex** [comment]
I was having this problem when building executables on a ruby 64bits and then running on a 32bits windows.

**Comment by scriptwizard99** [comment]
So this could be the reverse. 32bit running on 64?

**Comment by larsch** [comment]
Error 2 is "The system cannot find the file specified.", which could be a DLL missing from the target system, if I recall correctly. Perhaps try procmon from sysinternals to monitor what the system is doing while starting the executable.

**Comment by larsch** [comment]
Closing for now. Please reopen if additional information is available.
